/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExamDialog.java
 *
 * Created on 2009-11-24, 23:31:23
 */
package com.drowltd.dictionary.ui.desktop;

import com.drowltd.dictionary.core.db.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.BackingStoreException;
import java.util.prefs.Preferences;
import javax.swing.JOptionPane;


/**
 *
 * @author Miroslava
 */
public class ExamDialog extends javax.swing.JDialog {

    private Answers answer;
    private static final Preferences PREFS = Preferences.userNodeForPackage(SpellbookApp.class);
    private int seconds = 0;
    private int secondsBackup = 0;
    private boolean timerStatus = true;
    private int examWords;
    private int examWordsCopy;
    private int maximumSecondsProgressBar = 0;
    private int maximumWordsProgressBar = 0;
    private boolean returnTimerStatus;
    private boolean answerPressed = false;
    private boolean secHelper = false;
    private boolean firstRun =true;
    private Dictionary selectedDictionary = Dictionary.BG_EN;
    private ExamSettingsDialog examSettingsDialog = new ExamSettingsDialog(null, rootPaneCheckingEnabled);

    /** Creates new form ExamDialog */
    public ExamDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();


        System.out.println("asdasdasd " + PREFS.getBoolean("RETURN_TIMER_STATUS", modal) + "  " + PREFS.getInt("SECONDS", WIDTH));

        setTitle("Spellbook Exam");
        setLocationRelativeTo(parent);
       


        fromLanguageComboBox.addItem("Bulgarian");
        fromLanguageComboBox.addItem("English");
        toLanguageComboBox.addItem("English");
        toLanguageComboBox.addItem("Bulgarian");
        
        stopButton.setEnabled(false);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingsPanel = new javax.swing.JPanel();
        fromLanguageComboBox = new javax.swing.JComboBox();
        toLanguageComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        settingsButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        translateField = new javax.swing.JTextField();
        answerField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        stopButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        feedbackField = new javax.swing.JTextArea();
        timerProgressBar = new javax.swing.JProgressBar();
        difficultyLabel = new javax.swing.JLabel();
        answerButton = new javax.swing.JButton();
        wordsProgressBar = new javax.swing.JProgressBar();
        timerStatusLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        settingsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        fromLanguageComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fromLanguageComboBoxItemStateChanged(evt);
            }
        });

        jLabel1.setText("Select the languages for your exam:");

        jLabel2.setText("From:");

        jLabel3.setText("To:");

        jLabel6.setText("Place for some static picture/graphics");

        settingsButton.setText("Settings");
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout settingsPanelLayout = new javax.swing.GroupLayout(settingsPanel);
        settingsPanel.setLayout(settingsPanelLayout);
        settingsPanelLayout.setHorizontalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(settingsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(settingsPanelLayout.createSequentialGroup()
                        .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(toLanguageComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fromLanguageComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 130, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(60, 60, 60))))
            .addGroup(settingsPanelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(settingsButton)
                .addContainerGap(302, Short.MAX_VALUE))
        );
        settingsPanelLayout.setVerticalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fromLanguageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(toLanguageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(settingsButton)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        translateField.setEditable(false);

        answerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("Enter you answer here:");

        jLabel9.setText("Translate this word:");

        stopButton.setText("Stop");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        feedbackField.setBackground(new java.awt.Color(240, 240, 240));
        feedbackField.setColumns(20);
        feedbackField.setEditable(false);
        feedbackField.setFont(new java.awt.Font("Tahoma", 0, 11));
        feedbackField.setRows(4);
        feedbackField.setText("To start the exam press \"Run\"\nTo stop press \"Stop\"");
        jScrollPane1.setViewportView(feedbackField);

        timerProgressBar.setForeground(new java.awt.Color(51, 255, 51));
        timerProgressBar.setToolTipText("Timer");
        timerProgressBar.setString("Timer");
        timerProgressBar.setStringPainted(true);

        difficultyLabel.setText("Difficulty:");

        answerButton.setText("Answer");
        answerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerButtonActionPerformed(evt);
            }
        });

        wordsProgressBar.setForeground(new java.awt.Color(102, 102, 255));
        wordsProgressBar.setString("Words");
        wordsProgressBar.setStringPainted(true);

        timerStatusLabel.setText("Timer :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(answerField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(translateField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(startButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addComponent(stopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(difficultyLabel)
                                    .addComponent(timerStatusLabel))))
                        .addContainerGap())))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(answerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(timerProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wordsProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {startButton, stopButton});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stopButton)
                        .addComponent(startButton))
                    .addComponent(difficultyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(timerStatusLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(translateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(5, 5, 5)
                        .addComponent(answerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(answerButton))
                    .addComponent(jScrollPane1))
                .addGap(34, 34, 34)
                .addComponent(timerProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(wordsProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setText("Тук може да сложим бутони за бесеницата и детските игричи");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel10)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(settingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        if ((fromLanguageComboBox.getSelectedItem() == "English") && (toLanguageComboBox.getSelectedItem() == "Bulgarian")) {
            selectedDictionary = Dictionary.EN_BG;
        }

        answer = new Answers(selectedDictionary);
        dbCalling();

        if (ExamSettingsDialog.isOpen() == true) {
            examWords = ExamSettingsDialog.getWordsCount();
            examWordsCopy = ExamSettingsDialog.getWordsCount();
            PREFS.putInt("EXAM_WORDS", examWords);
        }

        if(PREFS.getBoolean("RETURN_TIMER_STATUS", true) == true)
         wordsProgressBar.setString("0/"+examWords);

        
        System.out.println("Seconds: " + seconds + " Seconds Backup: " + secondsBackup);
        System.out.println("Exam Words Left: " + examWords);

        if(timerStatusLabel.getText().equals("Timer: Initialized") || timerStatusLabel.getText().equals("Timer: Stopped")) {
            timerRunButton();
            timerStatusLabel.setText("Timer: Initialized");
        } else { startButton.setText("Next"); }

        secondsBackup = seconds;
    }//GEN-LAST:event_startButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        swingTimer.stop();
        timerProgressBar.setValue(0);
        timerStatusLabel.setText("Timer: Stopped");
        timerProgressBar.setString("Timer");
        startButton.setEnabled(true);
        settingsPanelEditability(true);
    }//GEN-LAST:event_stopButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        swingTimer.stop();
        PREFS.put("DIFF_LABEL", difficultyLabel.getText());
        if(timerStatusLabel.getText().contains("Stopped")){
            if(ExamSettingsDialog.returnTimerStatus() == true) {
                PREFS.put("TIMER_STATUS", "Timer: Initialized");
            } else { PREFS.put("TIMER_STATUS", "Timer: Not Initialized"); }
        } else { PREFS.put("TIMER_STATUS", timerStatusLabel.getText()); }
    }//GEN-LAST:event_formWindowClosed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        examSettingsDialog.showExamSettingsDialog();
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void answerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerFieldActionPerformed
        answered();
        seconds = 0;
        answerPressed = true;
    }//GEN-LAST:event_answerFieldActionPerformed

    private void answerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerButtonActionPerformed
        answered();
        seconds = 0;
        answerPressed = true;
    }//GEN-LAST:event_answerButtonActionPerformed

    private void fromLanguageComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fromLanguageComboBoxItemStateChanged
            if(fromLanguageComboBox.getSelectedIndex() == toLanguageComboBox.getSelectedIndex())
                System.out.println("CHECK IF IT'S WORKING");

    }//GEN-LAST:event_fromLanguageComboBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {



        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                ExamDialog dialog = new ExamDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    /*public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                    }*/                });
                dialog.setDefaultCloseOperation(ExamDialog.HIDE_ON_CLOSE);

                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton answerButton;
    private javax.swing.JTextField answerField;
    private static javax.swing.JLabel difficultyLabel;
    private javax.swing.JTextArea feedbackField;
    private javax.swing.JComboBox fromLanguageComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton settingsButton;
    private javax.swing.JPanel settingsPanel;
    private static javax.swing.JButton startButton;
    private static javax.swing.JButton stopButton;
    private javax.swing.JProgressBar timerProgressBar;
    private static javax.swing.JLabel timerStatusLabel;
    private javax.swing.JComboBox toLanguageComboBox;
    private javax.swing.JTextField translateField;
    private javax.swing.JProgressBar wordsProgressBar;
    // End of variables declaration//GEN-END:variables

    public void dbCalling() {

       translateField.setText(answer.getExamWord(selectedDictionary));

    }

    private void answered() {
        System.out.println("Answered");
        displayTranslation();
        dbCalling();
        answerField.setText(null);
        
    }

    private void displayTranslation() {
        answer.possibleAnswers();

        String str = (examWordsCopy - examWords + 1) + "/ " + examWordsCopy;
        System.out.println("displayTranslation" + examWordsCopy );
        if (answer.isCorrect(answerField.getText())) {

            wordsProgressBar.setForeground(new java.awt.Color(51, 255, 51));

            wordsProgressBar.setString(str);
            feedbackField.setText("Your answer is correct!");

        } else {

            wordsProgressBar.setString(str);
            wordsProgressBar.setForeground(new java.awt.Color(204, 0, 0));
            feedbackField.setText("Your answer is wrong!");
        }
    }

    private boolean flagLast = false;

    javax.swing.Timer swingTimer = new javax.swing.Timer(1 * 1000, new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent e) {

            if (examWords != 0) {
               if (flagLast) {
                  seconds = secondsBackup;
                   System.out.println("FlagLast is false");
                    System.out.println("Seconds left: " + seconds + " Sec backup: " + secondsBackup);
                    flagLast = false;
                    System.out.println("Words left: " + examWords + "backup "+ examWordsCopy);
                    
               }

                if (seconds >= 10) {

                    //timerField.setText("Time left: 00:" + seconds);
                    timerProgressBar.setString("Time left: 00:" + seconds);

                    System.out.println("Seconds " + seconds + "words copy" + examWordsCopy);

                    seconds--;
                    timerProgressBar.setValue(maximumSecondsProgressBar - seconds);
                    wordsProgressBar.setValue(maximumWordsProgressBar - examWords);
                    System.out.println(seconds);


                } else if (seconds < 10 && seconds >= 0) {

                   // timerField.setText("Time left: 00:0" + seconds);
                    timerProgressBar.setString("Time left: 00:0" + seconds);

                    System.out.println("Seconds " + seconds+"words copy" + examWordsCopy);

                    seconds--;
                    timerProgressBar.setValue(maximumSecondsProgressBar - seconds);
                    wordsProgressBar.setValue(maximumWordsProgressBar - examWords);

                    System.out.println(seconds);
                    if (seconds == -1) {
                        if (!answerPressed) {
                            System.out.println("Answered!Prekyswame!");
                            answered();
                        }
                        flagLast = true;
                        answerPressed = false;
                        examWords--;
                    }
                }
            } else {
                swingTimer.stop();
                timerStatusLabel.setText("Timer: Stopped");
                timerProgressBar.setString("Timer");
                wordsProgressBar.setValue(maximumWordsProgressBar);
                JOptionPane.showMessageDialog(rootPane, "All words have passed");

                startButton.setEnabled(true);
            }

        }
    });

    public static void diffLabelChange(String diff) {
        difficultyLabel.setText("Difficulty: " + diff);
    }

    public static void timerFieldLabel(String status) {
        timerStatusLabel.setText("Timer: " + status);
        if(status.matches("Not Initialized")){
            stopButton.setEnabled(false);
        } else { 
            stopButton.setEnabled(true);
            startButton.setText("Start");
        }
    }


    public void showExamDialog() {
        if (PREFS.getBoolean("RETURN_TIMER_STATUS", false) == true) {
            seconds = PREFS.getInt("SECONDS", WIDTH);
           
        }

       difficultyLabel.setText(PREFS.get("DIFF_LABEL", "Difficulty: Easy"));
       timerStatusLabel.setText(PREFS.get("TIMER_STATUS", "Timer: Not Initialized"));

        examWords = PREFS.getInt("EXAM_WORDS", 10);
        examWordsCopy = examWords;
        setVisible(true);
    }

    public void settingsPanelEditability (Boolean a) {

        fromLanguageComboBox.setEnabled(a);
        toLanguageComboBox.setEnabled(a);
        settingsButton.setEnabled(a);
    }

    public void timerRunButton () {
        seconds = ExamSettingsDialog.returnTimeSeconds();
        if(seconds == 0) {
            seconds = PREFS.getInt("SECONDS", WIDTH);
        } else {  PREFS.putInt("SECONDS", seconds); }
        System.out.println("SECONDA ARE NOW " + seconds);
            swingTimer.start();
            startButton.setEnabled(false);
            stopButton.setEnabled(true);
            maximumSecondsProgressBar = seconds;
            maximumWordsProgressBar = examWords;
            timerProgressBar.setMaximum(maximumSecondsProgressBar);
            wordsProgressBar.setMaximum(maximumWordsProgressBar);
    }

}




