/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WrongWords.java
 *
 * Created on 2009-12-24, 0:09:40
 */
package com.drowltd.dictionary.ui.desktop;

import java.awt.Font;
import java.util.ArrayList;

/**
 *
 * @author Franky
 */
public class WrongWordsDialog extends javax.swing.JDialog {

    ArrayList<String> wrongWords;
    ArrayList<String> correctTranslation;

    /** Creates new form WrongWords */
    public WrongWordsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        wrongWords = ExamDialog.getWrongWords();
        correctTranslation = ExamDialog.getCorrectTranslation();
        wrongWordsList.setListData(wrongWords.toArray());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        wrongWordsList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        correctTranslationTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        wrongWordsList.setBorder(javax.swing.BorderFactory.createTitledBorder("Wrong Words"));
        wrongWordsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                wrongWordsListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(wrongWordsList);

        correctTranslationTextArea.setColumns(20);
        correctTranslationTextArea.setRows(5);
        correctTranslationTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder("Correct Translation"));
        jScrollPane2.setViewportView(correctTranslationTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wrongWordsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_wrongWordsListValueChanged
        int firstIndex = evt.getFirstIndex();
        int lastIndex = evt.getLastIndex();
        correctTranslationTextArea.setFont(new Font("Serif", Font.ITALIC, 16));
        if (wrongWordsList.isSelectedIndex(firstIndex)) {
            correctTranslationTextArea.setText(correctTranslation.get(firstIndex));
        } else {
           correctTranslationTextArea.setText(correctTranslation.get(lastIndex));
        }

    }//GEN-LAST:event_wrongWordsListValueChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea correctTranslationTextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList wrongWordsList;
    // End of variables declaration//GEN-END:variables
}
