/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LearningWordsDialog.java
 *
 * Created on 2010-1-27, 17:01:30
 */
package com.drowltd.spellbook.ui.desktop.study;

import com.drowltd.spellbook.core.exception.DictionaryDbLockedException;
import com.drowltd.spellbook.core.preferences.PreferencesManager;
import static com.drowltd.spellbook.core.preferences.PreferencesManager.Preference;
import com.drowltd.spellbook.core.model.Dictionary;
import com.drowltd.spellbook.core.i18n.Translator;
import com.drowltd.spellbook.core.model.StudySet;
import com.drowltd.spellbook.core.model.StudySetEntry;
import com.drowltd.spellbook.core.service.DictionaryService;
import com.drowltd.spellbook.core.service.study.StudyService;
import com.drowltd.spellbook.ui.swing.component.DictionaryComboBox;
import com.drowltd.spellbook.ui.swing.util.IconManager;
import java.awt.Frame;
import java.util.List;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Random;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Sasho
 */
public class StudyWordsDialog extends javax.swing.JDialog {

    private StudyService studyService;
    private DictionaryService dictionaryService;
    private static final PreferencesManager PM = PreferencesManager.getInstance();
    private static final Translator TRANSLATOR = Translator.getTranslator("LearningWordsDialog");
    private SelectedDictionary selectedDictionary = SelectedDictionary.EN_BG;
    private String word;
    private WordsDialog wordsDialog;
    private List<String> wordsForLearning = new ArrayList<String>();
    private List<String> translationForLearning = new ArrayList<String>();
    private List shuffleWordsForLearning = new ArrayList<String>();
    private List shuffleTranslationForLearning = new ArrayList<String>();
    private List<Dictionary> dictionaries = new ArrayList<Dictionary>();
    private int wordIndex = 0;
    private long countOfWords;
    private Integer correctAnswer;
    private Integer wrongAnswer;
    private Integer answerSeen;
    private boolean isStopedLearn = true;
    private HowToEnumerate howToEnumerate = HowToEnumerate.IN_ORDER_OF_INPUT;
    private Frame parent;

    private enum SelectedDictionary {

        EN_BG, BG_EN
    }

    private enum HowToEnumerate {

        IN_ORDER_OF_INPUT, IN_REVERSE_ORDER_OF_INPUT, RANDOM
    }

    /** Creates new form LearningWordsDialog */
    public StudyWordsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        TRANSLATOR.reset();
        this.parent = parent;
        dictionaryService = DictionaryService.getInstance();
        dictionaries = dictionaryService.getDictionaries();
        initComponents();
        try {
            studyService = new StudyService();
        } catch (DictionaryDbLockedException ex) {
            Logger.getLogger(StudyWordsDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        setStudySetsInComboBox();
        ButtonGroup enumerateGroup = new ButtonGroup();
        enumerateGroup.add(inReverseOrderOfInputRadioButton);
        enumerateGroup.add(inOrderOfInputRadioButton);
        enumerateGroup.add(randomRadioButton);
        inOrderOfInputRadioButton.setSelected(true);
        answerButton.setEnabled(false);
        seeAnswerButton.setEnabled(false);
        stopButton.setEnabled(false);
        correctAnswer = new Integer(0);
        wrongAnswer = new Integer(0);
        answerSeen = new Integer(0);
        int index = PM.getInt(Preference.DICTIONARIES, dictionariesComboBox.getSelectedIndex());
        dictionariesComboBox.setSelectedIndex(index);
        String studySetName = (String) studySetsComboBox.getSelectedItem();
        countOfWords = studyService.getCountOfTheWords(studySetName);
        checkingTheDatabase();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        wordsButton = new javax.swing.JButton();
        warningIconLabel = new javax.swing.JLabel();
        firstRowLabel = new javax.swing.JLabel();
        secondRowLabel = new javax.swing.JLabel();
        dictionariesComboBox = new DictionaryComboBox(dictionaries);
        studySetsComboBox = new javax.swing.JComboBox();
        howToEnumeratePanel = new javax.swing.JPanel();
        randomRadioButton = new javax.swing.JRadioButton();
        inReverseOrderOfInputRadioButton = new javax.swing.JRadioButton();
        inOrderOfInputRadioButton = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        translateField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        answerField = new javax.swing.JTextField();
        answerButton = new javax.swing.JButton();
        answerStatutLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        countOfTheCorrectWordsLabel = new javax.swing.JLabel();
        countOfTheWrongWordsLabel = new javax.swing.JLabel();
        seeAnswerButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        answerSeenLabel = new javax.swing.JLabel();
        imoticonLabel = new javax.swing.JLabel();
        transcriptionLabel = new javax.swing.JLabel();
        repeatMisspelledWordsCheckBox = new javax.swing.JCheckBox();
        repeatWordCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("i18n/StudyWordsDialog"); // NOI18N
        setTitle(bundle.getString("LearningWordsDialog(Title)")); // NOI18N
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMaximumSize(new java.awt.Dimension(224, 159));

        jLabel1.setText(bundle.getString("Languages(Label)")); // NOI18N

        jLabel3.setText(bundle.getString("StudySet(Label)")); // NOI18N

        wordsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16x16/dictionary.png"))); // NOI18N
        wordsButton.setText(bundle.getString("Words(Button)")); // NOI18N
        wordsButton.setMaximumSize(new java.awt.Dimension(109, 25));
        wordsButton.setMinimumSize(new java.awt.Dimension(109, 25));
        wordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordsButtonActionPerformed(evt);
            }
        });

        warningIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24x24/warning.png"))); // NOI18N

        firstRowLabel.setText(bundle.getString("AddWordsFirstLabel(Message)")); // NOI18N

        studySetsComboBox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                studySetsComboBoxPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(warningIconLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstRowLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(secondRowLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(studySetsComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(dictionariesComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(wordsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dictionariesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studySetsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wordsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(firstRowLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(secondRowLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(warningIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {firstRowLabel, secondRowLabel});

        howToEnumeratePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        howToEnumeratePanel.setMaximumSize(new java.awt.Dimension(224, 159));
        howToEnumeratePanel.setMinimumSize(new java.awt.Dimension(224, 159));

        randomRadioButton.setText(bundle.getString("Random(Label)")); // NOI18N

        inReverseOrderOfInputRadioButton.setText(bundle.getString("InReverseOrderOfInput(Label)")); // NOI18N

        inOrderOfInputRadioButton.setText(bundle.getString("InOrderOfInput(Label)")); // NOI18N

        jLabel5.setText(bundle.getString("Enumerate(Label)")); // NOI18N

        javax.swing.GroupLayout howToEnumeratePanelLayout = new javax.swing.GroupLayout(howToEnumeratePanel);
        howToEnumeratePanel.setLayout(howToEnumeratePanelLayout);
        howToEnumeratePanelLayout.setHorizontalGroup(
            howToEnumeratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, howToEnumeratePanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(howToEnumeratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(randomRadioButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(inReverseOrderOfInputRadioButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(inOrderOfInputRadioButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addContainerGap())
        );
        howToEnumeratePanelLayout.setVerticalGroup(
            howToEnumeratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(howToEnumeratePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(inOrderOfInputRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inReverseOrderOfInputRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(randomRadioButton)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setMaximumSize(new java.awt.Dimension(492, 238));
        jPanel3.setMinimumSize(new java.awt.Dimension(492, 238));

        startButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16x16/media_play_green.png"))); // NOI18N
        startButton.setText(bundle.getString("Start(Button)")); // NOI18N
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        jLabel4.setText(bundle.getString("OverTranslateField(Label)")); // NOI18N

        translateField.setEditable(false);

        jLabel6.setText(bundle.getString("OverAnswerField(Label)")); // NOI18N

        answerField.setEditable(false);
        answerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerFieldActionPerformed(evt);
            }
        });

        answerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16x16/status_SuggestedAnswer.gif"))); // NOI18N
        answerButton.setText(bundle.getString("Answer(Button)")); // NOI18N
        answerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerButtonActionPerformed(evt);
            }
        });

        jLabel7.setText(bundle.getString("Correct(Label)")); // NOI18N

        jLabel8.setText(bundle.getString("Wrong(Label)")); // NOI18N

        seeAnswerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16x16/Bulb On.gif"))); // NOI18N
        seeAnswerButton.setText(bundle.getString("SeeAnswer(Button)")); // NOI18N
        seeAnswerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeAnswerButtonActionPerformed(evt);
            }
        });

        stopButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16x16/media_stop_red.png"))); // NOI18N
        stopButton.setText(bundle.getString("Stop(Button)")); // NOI18N
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        jLabel9.setText(bundle.getString("AnswerSeen(Label)")); // NOI18N

        transcriptionLabel.setText(" ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(translateField, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(answerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seeAnswerButton))
                    .addComponent(answerField, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addComponent(transcriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(stopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(answerSeenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                            .addComponent(countOfTheWrongWordsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(countOfTheCorrectWordsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(imoticonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(answerStatutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(142, 142, 142))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {answerButton, seeAnswerButton, startButton, stopButton});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(startButton)
                    .addComponent(stopButton)
                    .addComponent(jLabel7)
                    .addComponent(countOfTheCorrectWordsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(countOfTheWrongWordsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(translateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(answerSeenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(transcriptionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addComponent(imoticonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(answerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answerStatutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answerButton)
                    .addComponent(seeAnswerButton))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {answerButton, seeAnswerButton, startButton, stopButton});

        repeatMisspelledWordsCheckBox.setText(bundle.getString("RepeatMisspelledWords(CheckBox)")); // NOI18N
        repeatMisspelledWordsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repeatMisspelledWordsCheckBoxActionPerformed(evt);
            }
        });

        repeatWordCheckBox.setText(bundle.getString("RepeatWords(CheckBox)")); // NOI18N
        repeatWordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repeatWordCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(repeatWordCheckBox)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(repeatMisspelledWordsCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(howToEnumeratePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {howToEnumeratePanel, jPanel1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(howToEnumeratePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(repeatWordCheckBox)
                    .addComponent(repeatMisspelledWordsCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        startLearning();
    }//GEN-LAST:event_startButtonActionPerformed

    private void wordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordsButtonActionPerformed

        wordsDialog = new WordsDialog(parent, true);
        wordsDialog.clear();
        wordsDialog.setWordsInTable(false);
        wordsDialog.setLocationRelativeTo(this);
        wordsDialog.setVisible(true);

    }//GEN-LAST:event_wordsButtonActionPerformed

    private void answerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerButtonActionPerformed

        if (selectedDictionary == SelectedDictionary.EN_BG) {
            if (howToEnumerate == HowToEnumerate.RANDOM) {
                getAnswer(shuffleWordsForLearning, shuffleTranslationForLearning);
            } else {
                getAnswer(wordsForLearning, translationForLearning);
            }
        }
        if (selectedDictionary == SelectedDictionary.BG_EN) {
            if (howToEnumerate == HowToEnumerate.RANDOM) {
                getAnswer(shuffleTranslationForLearning, shuffleWordsForLearning);
            } else {
                getAnswer(translationForLearning, wordsForLearning);
            }
        }
    }//GEN-LAST:event_answerButtonActionPerformed

    private void seeAnswerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeAnswerButtonActionPerformed
        if (selectedDictionary == SelectedDictionary.EN_BG) {
            if (howToEnumerate == HowToEnumerate.RANDOM) {
                word = (String) shuffleTranslationForLearning.get(wordIndex);
            } else {
                word = translationForLearning.get(wordIndex);
            }
            String message = TRANSLATOR.translate("SeeAnswerMessege(Message)") + " \"" + word + "\"";
            JOptionPane.showMessageDialog(this, message, TRANSLATOR.translate("SeeAnswerPaneTittle(Title)"), JOptionPane.INFORMATION_MESSAGE);
        }
        if (selectedDictionary == SelectedDictionary.BG_EN) {
            if (howToEnumerate == HowToEnumerate.RANDOM) {
                word = (String) shuffleWordsForLearning.get(wordIndex);
            } else {
                word = wordsForLearning.get(wordIndex);
            }
            String message = TRANSLATOR.translate("SeeAnswerMessege(Message)") + " \"" + word + "\"";
            JOptionPane.showMessageDialog(this, message, TRANSLATOR.translate("SeeAnswerPaneTittle(Title)"), JOptionPane.INFORMATION_MESSAGE);
        }
        answerSeen++;
        answerSeenLabel.setText(answerSeen.toString());
        answerField.requestFocus();
    }//GEN-LAST:event_seeAnswerButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed

        setComponentsEnable(true);
        //answerField.setText(null);

    }//GEN-LAST:event_stopButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        PM.putInt(Preference.DICTIONARIES, dictionariesComboBox.getSelectedIndex());
        PM.putBoolean(Preference.LEARNING_IN_ORDER, inOrderOfInputRadioButton.isSelected());
        PM.putBoolean(Preference.LEARNING_IN_REVERSE_ORDER, inReverseOrderOfInputRadioButton.isSelected());
        PM.putBoolean(Preference.LEARNING_RANDOM, randomRadioButton.isSelected());
        PM.putBoolean(Preference.REPEAT_MISSPELLED_WORDS, repeatMisspelledWordsCheckBox.isSelected());
        PM.putBoolean(Preference.REPEAT_WORDS, repeatWordCheckBox.isSelected());

    }//GEN-LAST:event_formWindowClosed

    private void answerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerFieldActionPerformed
        if (!isStopedLearn) {
            if (selectedDictionary == SelectedDictionary.EN_BG) {
                if (howToEnumerate == HowToEnumerate.RANDOM) {
                    getAnswer(shuffleWordsForLearning, shuffleTranslationForLearning);
                } else {
                    getAnswer(wordsForLearning, translationForLearning);
                }
            }
            if (selectedDictionary == SelectedDictionary.BG_EN) {
                if (howToEnumerate == HowToEnumerate.RANDOM) {
                    getAnswer(shuffleTranslationForLearning, shuffleWordsForLearning);
                } else {
                    getAnswer(translationForLearning, wordsForLearning);
                }
            }
        }
    }//GEN-LAST:event_answerFieldActionPerformed

    private void repeatWordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repeatWordCheckBoxActionPerformed
        if (repeatWordCheckBox.isSelected()) {
            repeatMisspelledWordsCheckBox.setSelected(false);
        }
        if (!isStopedLearn) {
            answerField.requestFocus();
        }
    }//GEN-LAST:event_repeatWordCheckBoxActionPerformed

    private void repeatMisspelledWordsCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repeatMisspelledWordsCheckBoxActionPerformed
        if (repeatMisspelledWordsCheckBox.isSelected()) {
            repeatWordCheckBox.setSelected(false);
        }
        if (!isStopedLearn) {
            answerField.requestFocus();
        }
    }//GEN-LAST:event_repeatMisspelledWordsCheckBoxActionPerformed

    private void studySetsComboBoxPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_studySetsComboBoxPopupMenuWillBecomeInvisible
        checkingTheDatabase();
    }//GEN-LAST:event_studySetsComboBoxPopupMenuWillBecomeInvisible

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        setStudySetsInComboBox();
        int index = PM.getInt(Preference.STUDY_SETS, studySetsComboBox.getSelectedIndex());
        studySetsComboBox.setSelectedIndex(index);
        String studySetName = (String) studySetsComboBox.getSelectedItem();
        countOfWords = studyService.getCountOfTheWords(studySetName);
        checkingTheDatabase();
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        PM.putInt(Preference.STUDY_SETS, studySetsComboBox.getSelectedIndex());
    }//GEN-LAST:event_formWindowLostFocus
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton answerButton;
    private javax.swing.JTextField answerField;
    private javax.swing.JLabel answerSeenLabel;
    private javax.swing.JLabel answerStatutLabel;
    private javax.swing.JLabel countOfTheCorrectWordsLabel;
    private javax.swing.JLabel countOfTheWrongWordsLabel;
    private javax.swing.JComboBox dictionariesComboBox;
    private javax.swing.JLabel firstRowLabel;
    private javax.swing.JPanel howToEnumeratePanel;
    private javax.swing.JLabel imoticonLabel;
    private javax.swing.JRadioButton inOrderOfInputRadioButton;
    private javax.swing.JRadioButton inReverseOrderOfInputRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton randomRadioButton;
    private javax.swing.JCheckBox repeatMisspelledWordsCheckBox;
    private javax.swing.JCheckBox repeatWordCheckBox;
    private javax.swing.JLabel secondRowLabel;
    private javax.swing.JButton seeAnswerButton;
    private javax.swing.JButton startButton;
    private javax.swing.JButton stopButton;
    private javax.swing.JComboBox studySetsComboBox;
    private javax.swing.JLabel transcriptionLabel;
    private javax.swing.JTextField translateField;
    private javax.swing.JLabel warningIconLabel;
    private javax.swing.JButton wordsButton;
    // End of variables declaration//GEN-END:variables

    private void startLearning() {
        if (dictionariesComboBox.getSelectedIndex() == 0) {
            selectedDictionary = SelectedDictionary.EN_BG;
        }
        if (dictionariesComboBox.getSelectedIndex() == 1) {
            selectedDictionary = SelectedDictionary.BG_EN;
        }

        String studySetName = (String) studySetsComboBox.getSelectedItem();
        wordsForLearning = studyService.getWordsForStudy(studySetName);
        translationForLearning = studyService.getTranslationsForStudy(studySetName);

        setComponentsEnable(false);

        answerField.requestFocus();
        answerStatutLabel.setText(null);

        countOfTheCorrectWordsLabel.setText("0");
        countOfTheWrongWordsLabel.setText("0");
        answerSeenLabel.setText("0");

        correctAnswer = new Integer(0);
        wrongAnswer = new Integer(0);
        answerSeen = new Integer(0);

        if (inOrderOfInputRadioButton.isSelected()) {
            howToEnumerate = HowToEnumerate.IN_ORDER_OF_INPUT;
            wordIndex = 0;
            showWordWhenStartTheStudy(wordsForLearning, translationForLearning);
        }
        if (inReverseOrderOfInputRadioButton.isSelected()) {
            howToEnumerate = HowToEnumerate.IN_REVERSE_ORDER_OF_INPUT;

            long wordIndex1 = studyService.getCountOfTheWords(studySetName) - 1;
            wordIndex = (int) wordIndex1;

            showWordWhenStartTheStudy(wordsForLearning, translationForLearning);
        }
        if (randomRadioButton.isSelected()) {
            shuffle(wordsForLearning, translationForLearning);
            howToEnumerate = HowToEnumerate.RANDOM;
            wordIndex = 0;
            showWordWhenStartTheStudy(shuffleWordsForLearning, shuffleTranslationForLearning);
        }
    }

    private void showWordWhenStartTheStudy(List<String> words, List<String> translations) {
        String translation = null;
        if (selectedDictionary == SelectedDictionary.EN_BG) {
            word = words.get(wordIndex);
            translateField.setText(word);
            String transcription = getTranscription(word);
            transcriptionLabel.setText(" " + transcription);
        } else {
            translation = translations.get(wordIndex);
            translateField.setText(translation);
        }
    }

    private void shuffle(List words, List translations) {
        if (words.size() > 0 && translations.size() > 0) {

            List copyWords = new ArrayList();
            List copyTranslations = new ArrayList();

            for (Object object : words) {
                copyWords.add(object);
            }
            for (Object object : translations) {
                copyTranslations.add(object);
            }

            Random generator = new Random();

            do {
                int index = (int) (generator.nextDouble() * (double) copyWords.size());
                shuffleWordsForLearning.add(copyWords.remove(index));
                shuffleTranslationForLearning.add(copyTranslations.remove(index));
            } while (copyWords.size() > 0);
        }
    }

    private void getAnswer(List<String> words, List<String> translations) {
        String wordTranslation = answerField.getText();
        wordTranslation = wordTranslation.toLowerCase();

        if (wordTranslation == null || wordTranslation.isEmpty()) {
            JOptionPane.showMessageDialog(this, TRANSLATOR.translate("AnswerFeild(Message)"), null, JOptionPane.ERROR_MESSAGE);
            answerField.requestFocus();
        }

        List<String> possibleAnswers = new ArrayList<String>();
        String translation = translations.get(wordIndex);
        translation = translation.toLowerCase();
        translation = translation.replaceAll("\\b(n|a|v|(attr)|(adv)|[0-9]+)\\b\\s?", "");

        int i = 0;
        while (translation.charAt(i) == ' ') {
            translation = translation.substring(1);
        }

        String[] answers = Pattern.compile("\\s*[,|;|.|\\n]\\s*").split(translation, 0);

        for (String answer : answers) {
            possibleAnswers.add(answer);
        }
        if (repeatWordCheckBox.isSelected() && !wordTranslation.isEmpty()) {
            repeatWordIndex();
        }

        if (possibleAnswers.contains(wordTranslation)) {
            answerStatutLabel.setText(TRANSLATOR.translate("CorrectAnswer(Message)"));
            correctAnswer++;
            countOfTheCorrectWordsLabel.setText(correctAnswer.toString());
            imoticonLabel.setIcon(IconManager.getImageIcon("laugh.gif", IconManager.IconSize.SIZE48));
        } else {
            if (!wordTranslation.isEmpty()) {
                answerStatutLabel.setText(TRANSLATOR.translate("WrongAnswer(Message)"));
                imoticonLabel.setIcon(IconManager.getImageIcon("shy.gif", IconManager.IconSize.SIZE48));
                answerField.setText(null);
            }
            if (wordTranslation.isEmpty()) {
                answerStatutLabel.setText(null);
            }
            if (!wordTranslation.isEmpty()) {
                wrongAnswer++;
            }
            countOfTheWrongWordsLabel.setText(wrongAnswer.toString());

            if (repeatMisspelledWordsCheckBox.isSelected() && !wordTranslation.isEmpty()) {
                repeatWordIndex();
            }
        }
        if (howToEnumerate == HowToEnumerate.IN_ORDER_OF_INPUT) {
            if (!wordTranslation.isEmpty()) {
                wordIndex++;
            }
            if (wordIndex < countOfWords) {
                showNextWord(words);
            }
            if (wordIndex == countOfWords) {
                //stop study
                setComponentsEnable(true);
            }

            //answerField.setText(null);
        } else if (howToEnumerate == HowToEnumerate.IN_REVERSE_ORDER_OF_INPUT) {
            if (!wordTranslation.isEmpty()) {
                wordIndex--;
            }
            if (wordIndex >= 0) {
                showNextWord(words);
            }
            if (wordIndex == -1) {
                //stop study
                setComponentsEnable(true);
            }

            //answerField.setText(null);
        } else {
            if (!wordTranslation.isEmpty()) {
                wordIndex++;
            }
            if (wordIndex < countOfWords) {
                showNextWord(words);
            }
            if (wordIndex == countOfWords) {
                //stop study
                setComponentsEnable(true);
            }
        }
        answerField.requestFocus();
    }

    private void repeatWordIndex() {
        if (howToEnumerate == HowToEnumerate.IN_ORDER_OF_INPUT) {
            wordIndex--;
        }
        if (howToEnumerate == HowToEnumerate.IN_REVERSE_ORDER_OF_INPUT) {
            wordIndex++;
        }
        if (howToEnumerate == HowToEnumerate.RANDOM) {
            wordIndex--;
        }
    }

    private void showNextWord(List<String> words) {
        word = words.get(wordIndex);
        translateField.setText(word);
        String transcription = getTranscription(word);
        transcriptionLabel.setText(" " + transcription);
        answerField.setText(null);
    }

    private String getTranscription(String word) {
        String translation = null;

        if (selectedDictionary == SelectedDictionary.EN_BG) {
            translation = dictionaryService.getTranslation(word, dictionaries.get(0));
        }
        if (selectedDictionary == SelectedDictionary.BG_EN) {
            return " ";
        }

        int beginIndex = translation.indexOf('[');
        int endIndex = translation.indexOf(']') + 1;

        if (beginIndex == -1 && endIndex == 0) {
            return " ";
        }

        String transcription = translation.substring(beginIndex, endIndex);
        return transcription;
    }

    private void setComponentsEnable(boolean enable) {

        isStopedLearn = enable;
        answerButton.setEnabled(!enable);
        seeAnswerButton.setEnabled(!enable);
        stopButton.setEnabled(!enable);
        wordsButton.setEnabled(enable);
        startButton.setEnabled(enable);
        dictionariesComboBox.setEnabled(enable);
        studySetsComboBox.setEnabled(enable);
        inOrderOfInputRadioButton.setEnabled(enable);
        inReverseOrderOfInputRadioButton.setEnabled(enable);
        randomRadioButton.setEnabled(enable);
        transcriptionLabel.setText(" ");
        translateField.setText(null);
        answerField.setText(null);
        answerField.setEditable(!enable);
        startButton.requestFocus();
    }

    private void checkingTheDatabase() {
        List<StudySet> studySets = new ArrayList<StudySet>();
        studySets = studyService.getStudySets();

        if (studySets.isEmpty()) {
            reportThatDatabaseIsEmpty();
        } else {
            String studySetName = (String) studySetsComboBox.getSelectedItem();
            StudySet studySet = studyService.getStudySet(studySetName);
            Set<StudySetEntry> studySetEntry = studySet.getStudySetEntries();
            if (studySetEntry.isEmpty()) {
                reportThatDatabaseIsEmpty();
            } else {
                startButton.setEnabled(isStopedLearn);
                warningIconLabel.setIcon(null);
                firstRowLabel.setText(null);
                secondRowLabel.setText(null);
            }
        }
    }

    private void reportThatDatabaseIsEmpty() {
        startButton.setEnabled(false);
        warningIconLabel.setIcon(IconManager.getImageIcon("warning.png", IconManager.IconSize.SIZE24));
        firstRowLabel.setText(TRANSLATOR.translate("AddWordsFirstLabel(Message)"));
        secondRowLabel.setText(TRANSLATOR.translate("AddWordsSecondLabel(Message)"));
    }

    public void showLearningWordsDialog() {

        inOrderOfInputRadioButton.setSelected(PM.getBoolean(Preference.LEARNING_IN_ORDER, true));
        inReverseOrderOfInputRadioButton.setSelected(PM.getBoolean(Preference.LEARNING_IN_REVERSE_ORDER, false));
        randomRadioButton.setSelected(PM.getBoolean(Preference.LEARNING_RANDOM, false));
        repeatMisspelledWordsCheckBox.setSelected(PM.getBoolean(Preference.REPEAT_MISSPELLED_WORDS, true));
        repeatWordCheckBox.setSelected(PM.getBoolean(Preference.REPEAT_WORDS, false));

        setVisible(true);

    }

    private void setStudySetsInComboBox() {
        List<String> namesOfStudySets = new ArrayList<String>();
        namesOfStudySets = studyService.getNamesOfStudySets();
        studySetsComboBox.setModel(new DefaultComboBoxModel(namesOfStudySets.toArray()));
        //int index = PM.getInt(Preference.STUDY_SETS, studySetsComboBox.getSelectedIndex());
        //studySetsComboBox.setSelectedIndex(index);
    }
}
