package com.drowltd.dictionary.ui.desktop.exam;

import com.drowltd.dictionary.core.i18n.Translator;
import com.drowltd.dictionary.ui.desktop.IconManager;

/**
 *
 * @author miroslava
 * @since 0.2
 *
 */
public class ExamResult extends javax.swing.JDialog {

    private static final Translator TRANSLATOR = Translator.getTranslator("ExamResult");

    /** Creates new form ExamResult */
    public ExamResult(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        TRANSLATOR.reset();
        initComponents();

        setLocationRelativeTo(parent);
        setIconImage(IconManager.getImageIcon("teacher.png", IconManager.IconSize.SIZE16).getImage());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        okResultButton = new javax.swing.JButton();
        correctWordsLabel = new javax.swing.JLabel();
        correctWrodsResultLabel = new javax.swing.JLabel();
        wrongWordsLabel = new javax.swing.JLabel();
        wrongWrodsResultLabel = new javax.swing.JLabel();
        successRateLabel = new javax.swing.JLabel();
        successRateResultLabel = new javax.swing.JLabel();
        endLabel = new javax.swing.JLabel();
        seeWrongWords = new javax.swing.JButton();
        iconLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("i18n/ExamResult"); // NOI18N
        setTitle(bundle.getString("ExamResult(Title)")); // NOI18N

        okResultButton.setText("OK");
        okResultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okResultButtonActionPerformed(evt);
            }
        });

        correctWordsLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        java.util.ResourceBundle bundle1 = java.util.ResourceBundle.getBundle("i18n/ExamDialog"); // NOI18N
        correctWordsLabel.setText(bundle1.getString("CorrectWords(String)")); // NOI18N

        wrongWordsLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        wrongWordsLabel.setText(bundle1.getString("WrongWords(String)")); // NOI18N

        successRateLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        successRateLabel.setText(bundle.getString("Success(Label)")); // NOI18N

        endLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        endLabel.setAlignmentY(0.0F);

        seeWrongWords.setText(bundle1.getString("ShowWords(Button)")); // NOI18N
        seeWrongWords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeWrongWordsActionPerformed(evt);
            }
        });

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/48x48/bell2_green.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(endLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(okResultButton)
                                .addGap(35, 35, 35)
                                .addComponent(seeWrongWords))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(wrongWordsLabel)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(correctWordsLabel)
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(wrongWrodsResultLabel)
                                            .addComponent(correctWrodsResultLabel)
                                            .addComponent(successRateResultLabel)))
                                    .addComponent(successRateLabel))
                                .addGap(35, 35, 35)
                                .addComponent(iconLabel)))
                        .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(correctWordsLabel)
                            .addComponent(correctWrodsResultLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wrongWordsLabel)
                            .addComponent(wrongWrodsResultLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(successRateLabel)
                            .addComponent(successRateResultLabel))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iconLabel)
                        .addGap(46, 46, 46)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okResultButton)
                    .addComponent(seeWrongWords))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okResultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okResultButtonActionPerformed
        setVisible(false);
        ExamDialog.setFeedbackFieldDefault();
    }//GEN-LAST:event_okResultButtonActionPerformed

    private void seeWrongWordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeWrongWordsActionPerformed

        WrongWordsDialog wrongWordsDialog = new WrongWordsDialog(null, rootPaneCheckingEnabled);
        wrongWordsDialog.setVisible(true);
    }//GEN-LAST:event_seeWrongWordsActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel correctWordsLabel;
    private javax.swing.JLabel correctWrodsResultLabel;
    private javax.swing.JLabel endLabel;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okResultButton;
    private javax.swing.JButton seeWrongWords;
    private javax.swing.JLabel successRateLabel;
    private javax.swing.JLabel successRateResultLabel;
    private javax.swing.JLabel wrongWordsLabel;
    private javax.swing.JLabel wrongWrodsResultLabel;
    // End of variables declaration//GEN-END:variables

    public void showExamResult(int correctWords, int totalWords) {

        int uspeh = ((correctWords * 100) / totalWords);
        
        correctWrodsResultLabel.setText(Integer.toString(correctWords));
        wrongWrodsResultLabel.setText(Integer.toString(totalWords - correctWords));
        successRateResultLabel.setText(Integer.toString(uspeh) + "%");

        if (uspeh > 60) {
            endLabel.setText(TRANSLATOR.translate("Passed(Label)"));
            iconLabel.setIcon(IconManager.getImageIcon("bell2_green.png", IconManager.IconSize.SIZE48));
        } else {
            endLabel.setText(TRANSLATOR.translate("Failed(Label)"));
            iconLabel.setIcon(IconManager.getImageIcon("bell2_red.png", IconManager.IconSize.SIZE48));
        }
        setVisible(true);
    }
}
