package com.drowltd.spellbook.ui.desktop.exam;

import com.drowltd.spellbook.core.db.DatabaseService;
import com.drowltd.spellbook.core.db.Dictionary;
import com.drowltd.spellbook.ui.swing.model.ListBackedListModel;
import com.drowltd.spellbook.ui.swing.util.IconManager;

import java.util.List;

/**
 * @author Franky
 */
public class WrongWordsDialog extends javax.swing.JDialog {
    private DatabaseService databaseService = DatabaseService.getInstance();
    private Dictionary dictionary;

    /**
     * Creates new form WrongWords
     */
    public WrongWordsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setLocationRelativeTo(parent);
        setIconImage(IconManager.getImageIcon("teacher.png", IconManager.IconSize.SIZE16).getImage());
    }

    public void showDialog(Dictionary dictionary, List<String> wrongWords) {
        wrongWordsList.setModel(new ListBackedListModel(wrongWords));
        dictionary = dictionary;
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        wrongWordsList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        correctTranslationTextArea = new javax.swing.JTextArea();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Wrong Words");

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("i18n/WrongWordsDialog"); // NOI18N
        wrongWordsList.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("WrongWords(String)"))); // NOI18N
        wrongWordsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                wrongWordsListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(wrongWordsList);

        correctTranslationTextArea.setColumns(20);
        correctTranslationTextArea.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        correctTranslationTextArea.setRows(5);
        correctTranslationTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("CorrectTranslation(String)"))); // NOI18N
        jScrollPane2.setViewportView(correctTranslationTextArea);

        closeButton.setText(bundle.getString("Close(Button)")); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
                                .addComponent(closeButton, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeButton))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wrongWordsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_wrongWordsListValueChanged
        correctTranslationTextArea.setText(databaseService.getTranslation(dictionary, (String) wrongWordsList.getSelectedValue()));
    }//GEN-LAST:event_wrongWordsListValueChanged

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JTextArea correctTranslationTextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList wrongWordsList;
    // End of variables declaration//GEN-END:variables
}
