package com.drowltd.dictionary.ui.desktop;

import com.jgoodies.forms.layout.FormLayout;
import com.jgoodies.forms.layout.CellConstraints;
import com.drowltd.dictionary.core.db.DictDb;

import javax.swing.*;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.util.List;
import java.util.Random;

/**
 * User: bozhidar
 * Date: Sep 6, 2009
 * Time: 9:23:13 PM
 */
public class ExamPanel {
    private JPanel topPanel;
    private JTextField translationField;
    private JButton answerButton;
    private JButton skipButton;
    private JTextArea translationTextArea;
    private JLabel currentWordLabel;
    private JLabel scoreLabel;
    private JLabel statusLabel;
    private JLabel feedbackLabel;

    int currentWordNumber = 1;
    int wordsGuessed = 0;
    int maxWords = 10;

    List<String> words;
    DictDb dictDb = DictDb.getInstance();

    public ExamPanel() {
        updateScore();

        words = dictDb.getWordsFromSelectedDictionary();

        nextWord();

        answerButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String answer = translationField.getText();

                if (answer.length() > 0) {
                    String fullTranslation = dictDb.getTranslation(currentWordLabel.getText());

                    if (fullTranslation.contains(answer)) {
                        updateScore();
                        feedbackLabel.setText("Your guess was correct.");
                    } else {
                        nextWord();
                        feedbackLabel.setText("Your guess was incorrect");
                    }

                    translationTextArea.setText(fullTranslation);
                }

                translationField.setText(null);
                nextWord();
            }
        });

        skipButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                translationTextArea.setText(dictDb.getTranslation(currentWordLabel.getText()));
                nextWord();
                feedbackLabel.setText("You skipped the last word");
            }
        });
    }

    private void updateScore() {
        scoreLabel.setText("Score: " + wordsGuessed++ + "/" + maxWords);
    }

    private void nextWord() {
        if (currentWordNumber <= maxWords) {
            currentWordLabel.setText(words.get(new Random().nextInt(words.size())));
            statusLabel.setText(maxWords + 1 - currentWordNumber + " words remaining");
            currentWordNumber++;
        } else {
            JOptionPane.showMessageDialog(this.getComponent(), "Test completed");
            statusLabel.setText("Test completed");
        }
    }

    public JComponent getComponent() {
        return topPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        topPanel = new JPanel();
        topPanel.setLayout(new FormLayout("fill:87px:noGrow,left:4dlu:noGrow,fill:182px:noGrow,left:4dlu:noGrow,fill:83px:noGrow,left:4dlu:noGrow,fill:max(d;4px):grow", "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:10dlu:noGrow,top:4dlu:noGrow,center:d:grow,top:5dlu:noGrow,center:10dlu:noGrow"));
        final JLabel label1 = new JLabel();
        label1.setText("Word");
        CellConstraints cc = new CellConstraints();
        topPanel.add(label1, cc.xy(1, 1));
        final JLabel label2 = new JLabel();
        label2.setText("Translation");
        topPanel.add(label2, cc.xy(1, 3));
        currentWordLabel = new JLabel();
        currentWordLabel.setText("Label");
        topPanel.add(currentWordLabel, cc.xy(3, 1));
        translationField = new JTextField();
        topPanel.add(translationField, cc.xy(3, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        answerButton = new JButton();
        answerButton.setText("Answer");
        topPanel.add(answerButton, cc.xy(3, 5));
        scoreLabel = new JLabel();
        scoreLabel.setText("Score:");
        topPanel.add(scoreLabel, cc.xy(7, 5));
        skipButton = new JButton();
        skipButton.setText("Skip");
        topPanel.add(skipButton, cc.xy(5, 5));
        final JScrollPane scrollPane1 = new JScrollPane();
        topPanel.add(scrollPane1, cc.xyw(3, 9, 5, CellConstraints.FILL, CellConstraints.FILL));
        translationTextArea = new JTextArea();
        scrollPane1.setViewportView(translationTextArea);
        final JLabel label3 = new JLabel();
        label3.setText("Translation");
        topPanel.add(label3, cc.xy(1, 9));
        statusLabel = new JLabel();
        statusLabel.setText("No test in progress");
        topPanel.add(statusLabel, cc.xyw(1, 11, 7));
        feedbackLabel = new JLabel();
        feedbackLabel.setText("Press \"Answer\" or \"Skip\" to begin");
        topPanel.add(feedbackLabel, cc.xyw(3, 7, 5));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return topPanel;
    }
}
